github.com:
    git_protocol: https
    users:
        hamoncode:
            oauth_token: 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
    user: hamoncode
    oauth_token: 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
