[font]
size = 24

[colors.primary]
background = "0x143d20"  # Dark green grass, classic RCT look
foreground = "0xffe27e"  # Bright golden-yellow like the RCT UI

[colors.normal]
black = "0x2a1e0f"   # Deep brown, reminiscent of wooden rollercoasters
red = "0xcf3c31"     # Bright red like ride signs and rollercoaster tracks
green = "0x3faa5a"   # Vibrant park greenery
yellow = "0xffd400"  # Classic bright RCT balloon yellow
blue = "0x2879c3"    # Deep blue from water rides
magenta = "0xa040a0" # Purple from decorative elements
cyan = "0x3bbdc5"    # Light blue from water
white = "0xf7f3e0"   # Slightly aged paper-like UI text

[colors.bright]
black = "0x4b3820"   # Brighter wood tone
red = "0xff5f50"     # Bright ride entrance red
green = "0x63d471"   # Lush green bushes and trees
yellow = "0xffe97a"  # Sunlit golden signs
blue = "0x4faaff"    # Lighter blue for skies
magenta = "0xd678d7" # More vibrant purple details
cyan = "0x67eef0"    # Water reflection cyan
white = "0xffffff"   # Pure white for bright accents

[colors.cursor]
text = "0x143d20"     # Dark green text
cursor = "0xffa500"   # Bright orange cursor, like a coaster track

